version: "3"

services:
  db:
    container_name: ft-db
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata-ft
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_SERVER=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=${PGDATA}
    networks:
      - base_network
  web:
    container_name: ft-web
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - base_network

volumes:
  postgres-data:
  postgres-test-data:
  pgadmin-data:

networks:
  base_network:
    driver: bridge
