# Generated by Django 4.0.3 on 2022-03-28 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0002_product_barcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_type", models.CharField(choices=[("P", "product"), ("D", "dish")], max_length=1)),
                ("dish", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "meal",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "breakfast"), (1, "lunch"), (2, "dinner"), (3, "snack"), (4, "supper")]
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_entry",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_entry",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Diary entry",
                "verbose_name_plural": "Diary entries",
            },
        ),
    ]
