# Generated by Django 4.0.3 on 2022-03-28 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_barcode'),
        ('diary', '0002_alter_diaryentry_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diary_entry', to='products.product'),
        ),
    ]
