# Generated by Django 4.0.3 on 2022-04-01 19:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_barcode"),
        ("diary", "0003_alter_diaryentry_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="DishEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.RenameField(
            model_name="diaryentry",
            old_name="dish",
            new_name="dish_entry",
        ),
        migrations.RemoveField(
            model_name="diaryentry",
            name="product",
        ),
        migrations.CreateModel(
            name="ProductEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0, message="weight must be greater than 0")
                        ],
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="product_entry", to="products.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product entry",
                "verbose_name_plural": "Product entries",
            },
        ),
        migrations.AddField(
            model_name="diaryentry",
            name="product_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diary_entry",
                to="diary.productentry",
            ),
        ),
    ]
