# Generated by Django 4.0.3 on 2022-04-02 11:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_dish'),
        ('diary', '0004_dishentry_rename_dish_diaryentry_dish_entry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishentry',
            options={'verbose_name': 'Dish entry', 'verbose_name_plural': 'Dish entries'},
        ),
        migrations.AddField(
            model_name='dishentry',
            name='dish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dish_entry', to='products.dish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishentry',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0, message='weight must be greater than 0')]),
        ),
        migrations.AddField(
            model_name='productentry',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_entry', to='products.dish'),
        ),
    ]
