# Generated by Django 4.0.3 on 2022-05-14 17:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diary", "0006_remove_diaryentry_dish_entry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productentry",
            name="weight",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0, message="Waga musi być większa od 0")],
            ),
        ),
        migrations.CreateModel(
            name="GoalsEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "daily_kcal_goal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=0,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0, message="Wartość musi być większa od 0")
                        ],
                    ),
                ),
                (
                    "daily_protein_goal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0, message="Wartość musi być większa od 0")
                        ],
                    ),
                ),
                (
                    "daily_fat_goal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0, message="Wartość musi być większa od 0")
                        ],
                    ),
                ),
                (
                    "daily_carb_goal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0, message="Wartość musi być większa od 0")
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals_entry",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Goals entry",
                "verbose_name_plural": "Goals entries",
            },
        ),
    ]
