# Generated by Django 4.0.3 on 2022-05-14 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diary", "0007_alter_productentry_weight_goalsentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalsentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="goals_entry", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
