# Generated by Django 4.0.3 on 2022-05-14 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_alter_goalsentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalsentry',
            name='created_at',
        ),
        migrations.AddField(
            model_name='goalsentry',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 18, 2, 54, 582251, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
