# Generated by Django 4.0.3 on 2022-05-14 18:34

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_alter_goalsentry_from_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalsentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 18, 34, 20, 185022, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goalsentry',
            name='from_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
