# Generated by Django 4.0.3 on 2022-05-15 13:08

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0011_goalsentry_created_at_alter_goalsentry_from_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalsentry",
            name="from_date",
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
