# Generated by Django 4.0.3 on 2022-03-10 20:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "daily_kcal_goal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=0,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0, message="goal must be greater than 0")],
                    ),
                ),
                (
                    "daily_protein_goal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0, message="goal must be greater than 0")],
                    ),
                ),
                (
                    "daily_fat_goal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0, message="goal must be greater than 0")],
                    ),
                ),
                (
                    "daily_carb_goal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0, message="goal must be greater than 0")],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
    ]
