# Generated by Django 4.0.3 on 2022-05-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_carb_goal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='daily_fat_goal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='daily_kcal_goal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='daily_protein_goal',
        ),
    ]
